from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel
from typing import Literal, Optional
import json
import os
from pathlib import Path

PROXY_CONF_DIR = Path(os.getenv("PROXY_CONF_DIR", "/config/nginx/proxy-confs"))
NGINX_CONF_DIR = Path(os.getenv("NGINX_CONF_DIR", "/config/nginx"))
SWAG_CONTAINER = os.getenv("SWAG_CONTAINER_NAME", "swag")
METADATA_PREFIX = "## SWAG-UI: "
EDITABLE_CONF_FILES = {"nginx.conf", "proxy.conf", "resolver.conf", "ssl.conf"}

app = FastAPI(title="SWAG Proxy UI")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

try:
    import docker as docker_sdk
except ImportError:
    docker_sdk = None


# ── Models ────────────────────────────────────────────────────────────────────

class ExtraLocation(BaseModel):
    path: str
    upstream_host: str
    upstream_port: int = 80
    upstream_proto: Literal["http", "https"] = "http"
    websocket: bool = False
    allow_ips: list[str] = []


class ProxyHost(BaseModel):
    name: str
    type: Literal["subdomain", "subfolder"] = "subdomain"
    upstream_host: str
    upstream_port: int = 80
    upstream_proto: Literal["http", "https"] = "http"
    websocket: bool = False
    enabled: bool = True
    custom_location: Optional[str] = None
    client_max_body_size: str = "0"
    allow_ips: list[str] = []          # server-level (subdomain) / primary location (subfolder)
    extra_locations: list[ExtraLocation] = []


class ConfigFileUpdate(BaseModel):
    content: str


# ── Conf generation helpers ───────────────────────────────────────────────────

def build_location_block(
    path: str,
    upstream_host: str,
    upstream_port: int,
    upstream_proto: str,
    websocket: bool,
    allow_ips: list[str],
) -> str:
    lines = [
        f"    location {path} {{",
        "        include /config/nginx/proxy.conf;",
        "        include /config/nginx/resolver.conf;",
    ]
    for ip in allow_ips:
        lines.append(f"        allow {ip};")
    if allow_ips:
        lines.append("        deny all;")
    lines += [
        f"        set $upstream_app {upstream_host};",
        f"        set $upstream_port {upstream_port};",
        f"        set $upstream_proto {upstream_proto};",
        f"        proxy_pass $upstream_proto://$upstream_app:$upstream_port;",
    ]
    if websocket:
        lines += [
            "        proxy_set_header Upgrade $http_upgrade;",
            "        proxy_set_header Connection $connection_upgrade;",
        ]
    lines.append("    }")
    return "\n".join(lines)


def generate_subdomain_conf(host: ProxyHost) -> str:
    meta = json.dumps(host.model_dump())
    lines = [
        f"{METADATA_PREFIX}{meta}",
        "## Generated by SWAG Proxy UI",
        "",
        "server {",
        "    listen 443 ssl;",
        "    listen [::]:443 ssl;",
        "",
        f"    server_name {host.name}.*;",
        "",
        "    include /config/nginx/ssl.conf;",
        "",
        f"    client_max_body_size {host.client_max_body_size};",
    ]
    if host.allow_ips:
        lines.append("")
        for ip in host.allow_ips:
            lines.append(f"    allow {ip};")
        lines.append("    deny all;")
    lines.append("")
    lines.append(build_location_block(
        "/", host.upstream_host, host.upstream_port,
        host.upstream_proto, host.websocket, [],
    ))
    for loc in host.extra_locations:
        lines.append("")
        lines.append(build_location_block(
            loc.path, loc.upstream_host, loc.upstream_port,
            loc.upstream_proto, loc.websocket, loc.allow_ips,
        ))
    lines += ["}", ""]
    return "\n".join(lines)


def generate_subfolder_conf(host: ProxyHost) -> str:
    meta = json.dumps(host.model_dump())
    loc_path = host.custom_location or f"/{host.name}"
    lines = [
        f"{METADATA_PREFIX}{meta}",
        "## Generated by SWAG Proxy UI",
        "",
        f"location = {loc_path} {{",
        f"    return 301 $scheme://$host{loc_path}/;",
        "}",
        "",
        build_location_block(
            f"{loc_path}/", host.upstream_host, host.upstream_port,
            host.upstream_proto, host.websocket, host.allow_ips,
        ),
    ]
    for loc in host.extra_locations:
        lines.append("")
        lines.append(build_location_block(
            loc.path, loc.upstream_host, loc.upstream_port,
            loc.upstream_proto, loc.websocket, loc.allow_ips,
        ))
    lines.append("")
    return "\n".join(lines)


# ── File helpers ──────────────────────────────────────────────────────────────

def conf_filename(name: str, type_: str, enabled: bool) -> str:
    return f"{name}.{type_}.conf" + ("" if enabled else ".disabled")


def find_conf_file(name: str) -> Optional[tuple[Path, bool, str]]:
    for type_ in ["subdomain", "subfolder"]:
        for enabled in [True, False]:
            path = PROXY_CONF_DIR / conf_filename(name, type_, enabled)
            if path.exists():
                return path, enabled, type_
    return None


def parse_metadata(path: Path) -> Optional[dict]:
    try:
        first_line = path.open().readline().strip()
        if first_line.startswith(METADATA_PREFIX):
            return json.loads(first_line[len(METADATA_PREFIX):])
    except Exception:
        pass
    return None


# ── Proxy host endpoints ──────────────────────────────────────────────────────

@app.get("/api/proxy-hosts")
def list_proxy_hosts():
    if not PROXY_CONF_DIR.exists():
        return {"hosts": [], "warning": f"Config directory not found: {PROXY_CONF_DIR}"}

    hosts = []
    seen: set[str] = set()

    for path in sorted(PROXY_CONF_DIR.iterdir()):
        filename = path.name
        enabled = not filename.endswith(".disabled")
        name = filename[:-len(".disabled")] if not enabled else filename

        if name.endswith(".subdomain.conf"):
            host_name, host_type = name[:-len(".subdomain.conf")], "subdomain"
        elif name.endswith(".subfolder.conf"):
            host_name, host_type = name[:-len(".subfolder.conf")], "subfolder"
        else:
            continue

        if host_name in seen:
            continue
        seen.add(host_name)

        meta = parse_metadata(path)
        if meta:
            meta["enabled"] = enabled
            hosts.append({"managed": True, **meta})
        else:
            hosts.append({"managed": False, "name": host_name, "type": host_type, "enabled": enabled})

    return {"hosts": hosts}


@app.post("/api/proxy-hosts", status_code=201)
def create_proxy_host(host: ProxyHost):
    if find_conf_file(host.name):
        raise HTTPException(400, detail=f"Proxy host '{host.name}' already exists")
    path = PROXY_CONF_DIR / conf_filename(host.name, host.type, host.enabled)
    content = generate_subdomain_conf(host) if host.type == "subdomain" else generate_subfolder_conf(host)
    path.write_text(content)
    return host


@app.get("/api/proxy-hosts/{name}")
def get_proxy_host(name: str):
    result = find_conf_file(name)
    if not result:
        raise HTTPException(404, detail=f"Proxy host '{name}' not found")
    path, enabled, _ = result
    meta = parse_metadata(path)
    if not meta:
        raise HTTPException(422, detail="Conf file has no SWAG-UI metadata (unmanaged file)")
    meta["enabled"] = enabled
    return meta


@app.put("/api/proxy-hosts/{name}")
def update_proxy_host(name: str, host: ProxyHost):
    result = find_conf_file(name)
    if not result:
        raise HTTPException(404, detail=f"Proxy host '{name}' not found")
    result[0].unlink()
    path = PROXY_CONF_DIR / conf_filename(host.name, host.type, host.enabled)
    content = generate_subdomain_conf(host) if host.type == "subdomain" else generate_subfolder_conf(host)
    path.write_text(content)
    return host


@app.delete("/api/proxy-hosts/{name}", status_code=204)
def delete_proxy_host(name: str):
    result = find_conf_file(name)
    if not result:
        raise HTTPException(404, detail=f"Proxy host '{name}' not found")
    result[0].unlink()


@app.post("/api/proxy-hosts/{name}/toggle")
def toggle_proxy_host(name: str):
    result = find_conf_file(name)
    if not result:
        raise HTTPException(404, detail=f"Proxy host '{name}' not found")
    path, enabled, host_type = result
    new_path = PROXY_CONF_DIR / conf_filename(name, host_type, not enabled)
    path.rename(new_path)
    return {"name": name, "enabled": not enabled}


@app.get("/api/proxy-hosts/{name}/parse")
def parse_unmanaged_conf(name: str):
    """Extract structured settings from an unmanaged conf file for onboarding."""
    result = find_conf_file(name)
    if not result:
        raise HTTPException(404, detail=f"Proxy host '{name}' not found")
    path, enabled, type_ = result

    content = path.read_text()

    import re

    def search(pattern, default=None):
        m = re.search(pattern, content)
        return m.group(1) if m else default

    return {
        "name": name,
        "type": type_,
        "enabled": enabled,
        "upstream_host": search(r"set \$upstream_app\s+(\S+);", ""),
        "upstream_port": int(search(r"set \$upstream_port\s+(\d+);", "80")),
        "upstream_proto": search(r"set \$upstream_proto\s+(https?);", "http"),
        "websocket": bool(re.search(r"proxy_set_header\s+Upgrade", content, re.IGNORECASE)),
        "client_max_body_size": search(r"client_max_body_size\s+(\S+);", "0"),
        "allow_ips": [],
        "extra_locations": [],
        "custom_location": None,
        "raw_conf": content,
    }


@app.get("/api/proxy-hosts/{name}/conf")
def get_conf_content(name: str):
    result = find_conf_file(name)
    if not result:
        raise HTTPException(404, detail=f"Proxy host '{name}' not found")
    return {"content": result[0].read_text(), "filename": result[0].name}


# ── Nginx config file endpoints ───────────────────────────────────────────────

@app.get("/api/nginx-configs")
def list_nginx_configs():
    result = []
    for filename in sorted(EDITABLE_CONF_FILES):
        path = NGINX_CONF_DIR / filename
        result.append({"filename": filename, "exists": path.exists()})
    return result


@app.get("/api/nginx-configs/{filename}")
def get_nginx_config(filename: str):
    if filename not in EDITABLE_CONF_FILES:
        raise HTTPException(400, detail=f"Not an editable file: {filename}")
    path = NGINX_CONF_DIR / filename
    if not path.exists():
        raise HTTPException(404, detail=f"{filename} not found — is /config/nginx mounted?")
    return {"filename": filename, "content": path.read_text()}


@app.put("/api/nginx-configs/{filename}")
def update_nginx_config(filename: str, body: ConfigFileUpdate):
    if filename not in EDITABLE_CONF_FILES:
        raise HTTPException(400, detail=f"Not an editable file: {filename}")
    path = NGINX_CONF_DIR / filename
    if not path.exists():
        raise HTTPException(404, detail=f"{filename} not found")
    path.write_text(body.content)
    return {"filename": filename, "message": "saved"}


# ── Nginx reload endpoint ─────────────────────────────────────────────────────

@app.post("/api/nginx/reload")
def reload_nginx():
    if docker_sdk is None:
        raise HTTPException(503, detail="Docker SDK not installed in this image")

    try:
        client = docker_sdk.from_env()
    except Exception as e:
        raise HTTPException(503, detail=f"Docker socket unavailable. Mount /var/run/docker.sock:ro\n{e}")

    try:
        container = client.containers.get(SWAG_CONTAINER)
    except Exception:
        raise HTTPException(404, detail=f"Container '{SWAG_CONTAINER}' not found. Set SWAG_CONTAINER_NAME env var.")

    # Test config first
    test = container.exec_run("nginx -t")
    test_output = test.output.decode() if test.output else ""
    if test.exit_code != 0:
        raise HTTPException(422, detail=f"Config test failed — reload aborted:\n{test_output}")

    # Reload
    reload = container.exec_run("nginx -s reload")
    if reload.exit_code != 0:
        output = reload.output.decode() if reload.output else ""
        raise HTTPException(500, detail=f"Reload failed:\n{output}")

    return {"message": "nginx reloaded successfully", "test_output": test_output}


# ── Health ────────────────────────────────────────────────────────────────────

@app.get("/api/health")
def health():
    return {
        "status": "ok",
        "conf_dir": str(PROXY_CONF_DIR),
        "conf_dir_exists": PROXY_CONF_DIR.exists(),
        "nginx_conf_dir": str(NGINX_CONF_DIR),
        "nginx_conf_dir_exists": NGINX_CONF_DIR.exists(),
        "docker_available": docker_sdk is not None,
        "swag_container": SWAG_CONTAINER,
    }


# Serve built frontend in production
static_dir = Path("static")
if static_dir.exists():
    app.mount("/", StaticFiles(directory=str(static_dir), html=True), name="static")
