from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel
from typing import Literal, Optional
import os
import re
from pathlib import Path

PROXY_CONF_DIR = Path("/config/nginx/proxy-confs")
NGINX_CONF_DIR = Path("/config/nginx")
DNS_CONF_DIR   = Path("/config/dns-conf")
SITE_CONF_DIR  = Path("/config/nginx/site-confs")
LOG_DIR        = Path("/config/log")
FAIL2BAN_DIR   = Path("/config/fail2ban")
SWAG_CONTAINER = os.getenv("SWAG_CONTAINER_NAME", "swag")

# Maximum bytes to return from a single log file (tail)
LOG_MAX_BYTES = 200 * 1024  # 200 KB
EDITABLE_CONF_FILES = {"nginx.conf", "proxy.conf", "resolver.conf", "ssl.conf"}

# (suffix, type, enabled, is_sample)
CONF_SUFFIXES = [
    (".subdomain.conf",          "subdomain", True,  False),
    (".subdomain.conf.disabled", "subdomain", False, False),
    (".subdomain.conf.sample",   "subdomain", False, True),
    (".subfolder.conf",          "subfolder", True,  False),
    (".subfolder.conf.disabled", "subfolder", False, False),
    (".subfolder.conf.sample",   "subfolder", False, True),
]

FALLBACK_TEMPLATES = {
    "subdomain": """\
## {name}.subdomain.conf — adjust upstream details and save

server {{
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name {name}.*;

    include /config/nginx/ssl.conf;

    client_max_body_size 0;

    location / {{
        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app {name};
        set $upstream_port 80;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;
    }}
}}
""",
    "subfolder": """\
## {name}.subfolder.conf — adjust upstream details and save

location = /{name} {{
    return 301 $scheme://$host/{name}/;
}}

location /{name}/ {{
    include /config/nginx/proxy.conf;
    include /config/nginx/resolver.conf;
    set $upstream_app {name};
    set $upstream_port 80;
    set $upstream_proto http;
    proxy_pass $upstream_proto://$upstream_app:$upstream_port;
}}
""",
}

_SWAG_UI_PREFIXES = ("## SWAG-UI: ", "## Generated by SWAG Proxy UI")

AUTH_PROVIDERS = {"authelia", "authentik", "ldap", "tinyauth"}

DEFAULT_AUTH_TEMPLATES: dict[str, dict[str, str]] = {
    "authelia": {
        "server": """\
## Authelia server-block snippet
## https://www.authelia.com/integration/proxies/nginx/

location = /authelia/api/authz/auth-request {
    internal;

    proxy_pass              http://authelia:9091/api/authz/auth-request;

    proxy_pass_request_body off;
    proxy_set_header        Content-Length "";
    proxy_set_header        X-Original-URL $scheme://$http_host$request_uri;
    proxy_set_header        X-Forwarded-Method $request_method;
    proxy_set_header        X-Forwarded-Proto $scheme;
    proxy_set_header        X-Forwarded-Host $http_host;
    proxy_set_header        X-Forwarded-URI $request_uri;
    proxy_set_header        X-Forwarded-For $remote_addr;
    proxy_set_header        X-Original-Method $request_method;
    proxy_set_header        X-Original-URI $request_uri;
    proxy_set_header        X-Real-IP $remote_addr;
}

location @authelia_proxy_signin {
    internal;
    add_header Set-Cookie $authelia_redirect_cookie;
    return 302 https://authelia.example.com/;
}
""",
        "location": """\
## Authelia location-block snippet
auth_request /authelia/api/authz/auth-request;
auth_request_set $user   $upstream_http_remote_user;
auth_request_set $groups $upstream_http_remote_groups;
auth_request_set $name   $upstream_http_remote_name;
auth_request_set $emails $upstream_http_remote_emails;

proxy_set_header Remote-User   $user;
proxy_set_header Remote-Groups $groups;
proxy_set_header Remote-Name   $name;
proxy_set_header Remote-Emails $emails;

error_page 401 =302 https://authelia.example.com/;
""",
    },
    "authentik": {
        "server": """\
## Authentik server-block snippet
## https://goauthentik.io/docs/providers/proxy/nginx

location /outpost.goauthentik.io {
    proxy_pass          https://authentik:9443/outpost.goauthentik.io;
    proxy_set_header    Host $host;
    proxy_set_header    X-Original-URL $scheme://$http_host$request_uri;
    add_header          Set-Cookie $auth_cookie;
    auth_request_set    $auth_cookie $upstream_http_set_cookie;
    proxy_pass_request_body off;
    set                 $null '';
    proxy_set_header    Content-Length $null;
}

location @goauthentik_proxy_signin {
    internal;
    add_header Set-Cookie $auth_cookie;
    return 302 /outpost.goauthentik.io/start?rd=$request_uri;
}
""",
        "location": """\
## Authentik location-block snippet
auth_request /outpost.goauthentik.io/auth/nginx;
error_page 401 = @goauthentik_proxy_signin;
auth_request_set $auth_cookie $upstream_http_set_cookie;
add_header Set-Cookie $auth_cookie;

auth_request_set $authentik_username $upstream_http_x_authentik_username;
auth_request_set $authentik_groups   $upstream_http_x_authentik_groups;
auth_request_set $authentik_email    $upstream_http_x_authentik_email;
auth_request_set $authentik_name     $upstream_http_x_authentik_name;
auth_request_set $authentik_uid      $upstream_http_x_authentik_uid;

proxy_set_header X-authentik-username $authentik_username;
proxy_set_header X-authentik-groups   $authentik_groups;
proxy_set_header X-authentik-email    $authentik_email;
proxy_set_header X-authentik-name     $authentik_name;
proxy_set_header X-authentik-uid      $authentik_uid;
""",
    },
    "ldap": {
        "server": """\
## LDAP server-block snippet (linuxserver/ldap-auth)

location /ldaplogin {
    proxy_pass http://ldap-auth:9000;
    proxy_pass_request_body off;
    proxy_set_header Content-Length "";
    proxy_set_header X-Target $proxy_proto_addr;
    proxy_set_header X-Username '';
    proxy_set_header X-Url $scheme://$http_host$request_uri;
    proxy_set_header X-Cookie-Name "ZNC_Auth";
    proxy_set_header Cookie $http_cookie;
}

location = /auth {
    internal;
    proxy_pass http://ldap-auth:8888;
    proxy_pass_request_body off;
    proxy_set_header Content-Length "";
    proxy_set_header X-Ldap-URL      "ldap://ldap.example.com:389";
    proxy_set_header X-Ldap-Base     "dc=example,dc=com";
    proxy_set_header X-Ldap-Binddn   "cn=admin,dc=example,dc=com";
    proxy_set_header X-Ldap-Bindpasswd "";
    proxy_set_header X-Ldap-Group    "(|(memberUid=$remote_user))";
    proxy_set_header X-CookieName    "ZNC_Auth";
    proxy_set_header Cookie $http_cookie;
}
""",
        "location": """\
## LDAP location-block snippet
auth_request /auth;
error_page 401 =200 /ldaplogin;
""",
    },
    "tinyauth": {
        "server": """\
## TinyAuth server-block snippet
## https://github.com/steveiliop56/tinyauth

location = /tinyauth {
    internal;
    proxy_pass http://tinyauth:3000/api/auth/nginx;
    proxy_set_header X-Original-URI $request_uri;
    proxy_set_header X-Original-URL $scheme://$host$request_uri;
    proxy_pass_request_body off;
    proxy_set_header Content-Length "";
}

location @tinyauth_login {
    internal;
    set $domain $scheme://$host;
    return 302 http://tinyauth:3000/?redirect=$domain$request_uri;
}
""",
        "location": """\
## TinyAuth location-block snippet
auth_request /tinyauth;
error_page 401 = @tinyauth_login;
""",
    },
}

app = FastAPI(title="SWAG Proxy UI")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

try:
    import docker as docker_sdk
except ImportError:
    docker_sdk = None


# ── Models ────────────────────────────────────────────────────────────────────

class NewHostRequest(BaseModel):
    name: str
    type: Literal["subdomain", "subfolder"] = "subdomain"


class ConfigFileUpdate(BaseModel):
    content: str


class NewConfigFile(BaseModel):
    filename: str


class IpRequest(BaseModel):
    ip: str


# ── File helpers ──────────────────────────────────────────────────────────────

def parse_conf_filename(fn: str) -> Optional[tuple[str, str, bool, bool]]:
    """Returns (name, type, enabled, is_sample) or None. Skips _template files."""
    for suffix, type_, enabled, is_sample in CONF_SUFFIXES:
        if fn.endswith(suffix):
            name = fn[:-len(suffix)]
            if not name or name.startswith("_template"):
                return None
            return name, type_, enabled, is_sample
    return None


def find_conf(name: str) -> Optional[tuple[Path, str, bool, bool]]:
    """Find any proxy conf for name. Returns (path, type, enabled, is_sample)."""
    for suffix, type_, enabled, is_sample in CONF_SUFFIXES:
        path = PROXY_CONF_DIR / f"{name}{suffix}"
        if path.exists():
            return path, type_, enabled, is_sample
    return None


def strip_swag_header(content: str) -> str:
    """Remove legacy ## SWAG-UI metadata lines from the top of a conf file."""
    lines = content.splitlines(keepends=True)
    while lines and any(lines[0].startswith(p) for p in _SWAG_UI_PREFIXES):
        lines.pop(0)
    if lines and lines[0].strip() == "":
        lines.pop(0)
    return "".join(lines)


# ── Proxy host endpoints ──────────────────────────────────────────────────────

@app.get("/api/proxy-hosts")
def list_proxy_hosts():
    if not PROXY_CONF_DIR.exists():
        return {"hosts": [], "warning": f"Config directory not found: {PROXY_CONF_DIR}"}

    hosts = []
    seen: set[str] = set()

    for path in sorted(PROXY_CONF_DIR.iterdir()):
        parsed = parse_conf_filename(path.name)
        if not parsed:
            continue
        name, type_, enabled, is_sample = parsed
        key = f"{name}.{type_}"
        if key in seen:
            continue
        seen.add(key)
        hosts.append({"name": name, "type": type_, "enabled": enabled, "is_sample": is_sample})

    return {"hosts": hosts}


@app.post("/api/proxy-hosts", status_code=201)
def create_proxy_host(req: NewHostRequest):
    """Create a new .conf from the SWAG _template file (or built-in fallback)."""
    name = req.name.strip().lower()
    if not re.match(r'^[a-z0-9][a-z0-9-]*$', name):
        raise HTTPException(400, detail="Name must be lowercase alphanumeric + hyphens")
    if find_conf(name):
        raise HTTPException(400, detail=f"'{name}' already exists")

    template_path = PROXY_CONF_DIR / f"_template.{req.type}.conf.sample"
    if template_path.exists():
        content = template_path.read_text()
    else:
        content = FALLBACK_TEMPLATES[req.type].format(name=name)

    dest = PROXY_CONF_DIR / f"{name}.{req.type}.conf"
    dest.write_text(content)
    return {"name": name, "type": req.type, "content": content}


@app.get("/api/proxy-hosts/{name}/content")
def get_proxy_host_content(name: str):
    result = find_conf(name)
    if not result:
        raise HTTPException(404, detail=f"Proxy host '{name}' not found")
    path, type_, enabled, is_sample = result
    content = strip_swag_header(path.read_text())
    return {"name": name, "type": type_, "enabled": enabled, "is_sample": is_sample, "content": content}


@app.put("/api/proxy-hosts/{name}/content")
def update_proxy_host_content(name: str, body: ConfigFileUpdate):
    result = find_conf(name)
    if not result:
        raise HTTPException(404, detail=f"Proxy host '{name}' not found")
    result[0].write_text(body.content)
    return {"name": name, "message": "saved"}


@app.delete("/api/proxy-hosts/{name}", status_code=204)
def delete_proxy_host(name: str):
    """Delete the active .conf. Any .conf.sample template is left in place,
    so a host enabled from a sample reverts to that sample on delete."""
    result = find_conf(name)
    if not result:
        raise HTTPException(404, detail=f"Proxy host '{name}' not found")
    result[0].unlink()


@app.post("/api/proxy-hosts/{name}/enable-sample")
def enable_sample(name: str):
    """Duplicate {name}.{type}.conf.sample → {name}.{type}.conf and return its
    content for the editor. The sample template is kept."""
    result = find_conf(name)
    if not result:
        raise HTTPException(404, detail=f"Proxy host '{name}' not found")
    path, type_, _, is_sample = result
    if not is_sample:
        raise HTTPException(400, detail=f"'{name}' is not a sample file")
    content = path.read_text()
    dest = PROXY_CONF_DIR / f"{name}.{type_}.conf"
    dest.write_text(content)
    return {"name": name, "type": type_, "content": content}


# ── Nginx config file endpoints ───────────────────────────────────────────────

def _is_system_nginx_conf(filename: str) -> bool:
    """Files managed elsewhere — not surfaced as user 'custom' configs."""
    if filename in EDITABLE_CONF_FILES:
        return True
    for provider in AUTH_PROVIDERS:
        if filename in (f"{provider}-server.conf", f"{provider}-location.conf"):
            return True
    return False


def _nginx_conf_path(filename: str) -> Path:
    """Resolve and validate a .conf filename in /config/nginx (no traversal)."""
    if not filename or "/" in filename or "\\" in filename:
        raise HTTPException(400, detail="Invalid filename")
    if not filename.endswith(".conf"):
        raise HTTPException(400, detail="Filename must end in .conf")
    path = NGINX_CONF_DIR / filename
    if not path.resolve().is_relative_to(NGINX_CONF_DIR.resolve()):
        raise HTTPException(400, detail="Invalid filename")
    return path


@app.get("/api/nginx-configs")
def list_nginx_configs():
    """Core editable files + any user-created custom .conf files."""
    core = [
        {"filename": f, "exists": (NGINX_CONF_DIR / f).exists()}
        for f in sorted(EDITABLE_CONF_FILES)
    ]
    custom = []
    if NGINX_CONF_DIR.exists():
        for path in sorted(NGINX_CONF_DIR.glob("*.conf")):
            if path.is_file() and not _is_system_nginx_conf(path.name):
                custom.append({"filename": path.name})
    return {"core": core, "custom": custom}


@app.post("/api/nginx-configs", status_code=201)
def create_nginx_config(body: NewConfigFile):
    name = body.filename.strip()
    if not name.endswith(".conf"):
        name += ".conf"
    if _is_system_nginx_conf(name):
        raise HTTPException(400, detail=f"'{name}' is a reserved file")
    path = _nginx_conf_path(name)
    if path.exists():
        raise HTTPException(400, detail=f"'{name}' already exists")
    path.write_text("")
    return {"filename": name, "content": ""}


@app.get("/api/nginx-configs/{filename}")
def get_nginx_config(filename: str):
    path = _nginx_conf_path(filename)
    if not path.exists():
        raise HTTPException(404, detail=f"{filename} not found — is /config/nginx mounted?")
    return {"filename": filename, "content": path.read_text()}


@app.put("/api/nginx-configs/{filename}")
def update_nginx_config(filename: str, body: ConfigFileUpdate):
    path = _nginx_conf_path(filename)
    if not path.exists():
        raise HTTPException(404, detail=f"{filename} not found")
    path.write_text(body.content)
    return {"filename": filename, "message": "saved"}


@app.delete("/api/nginx-configs/{filename}", status_code=204)
def delete_nginx_config(filename: str):
    if _is_system_nginx_conf(filename):
        raise HTTPException(400, detail="Cannot delete a system config file")
    path = _nginx_conf_path(filename)
    if not path.exists():
        raise HTTPException(404, detail=f"{filename} not found")
    path.unlink()


# ── Nginx reload endpoint ─────────────────────────────────────────────────────

@app.post("/api/nginx/reload")
def reload_nginx():
    if docker_sdk is None:
        raise HTTPException(503, detail="Docker SDK not installed in this image")

    try:
        client = docker_sdk.from_env()
    except Exception as e:
        raise HTTPException(503, detail=f"Docker socket unavailable. Mount /var/run/docker.sock:ro\n{e}")

    try:
        container = client.containers.get(SWAG_CONTAINER)
    except Exception:
        raise HTTPException(404, detail=f"Container '{SWAG_CONTAINER}' not found. Set SWAG_CONTAINER_NAME env var.")

    # Test config first
    test = container.exec_run("nginx -t")
    test_output = test.output.decode() if test.output else ""
    if test.exit_code != 0:
        raise HTTPException(422, detail=f"Config test failed — reload aborted:\n{test_output}")

    # Reload
    reload = container.exec_run("nginx -s reload")
    if reload.exit_code != 0:
        output = reload.output.decode() if reload.output else ""
        raise HTTPException(500, detail=f"Reload failed:\n{output}")

    return {"message": "nginx reloaded successfully", "test_output": test_output}


# ── Auth config endpoints ─────────────────────────────────────────────────────

def _auth_conf_path(provider: str, level: str) -> Path:
    return NGINX_CONF_DIR / f"{provider}-{level}.conf"


def _auth_status(provider: str, level: str) -> str:
    if _auth_conf_path(provider, level).exists():
        return "active"
    if (NGINX_CONF_DIR / f"{provider}-{level}.conf.sample").exists():
        return "sample"
    return "new"


def _auth_content(provider: str, level: str) -> str:
    """Return content for editor: active → sample → built-in template."""
    conf = _auth_conf_path(provider, level)
    if conf.exists():
        return conf.read_text()
    sample = NGINX_CONF_DIR / f"{provider}-{level}.conf.sample"
    if sample.exists():
        return sample.read_text()
    return DEFAULT_AUTH_TEMPLATES.get(provider, {}).get(level, "")


def _check_auth_args(provider: str, level: str) -> None:
    if provider not in AUTH_PROVIDERS:
        raise HTTPException(400, detail=f"Unknown auth provider: {provider}")
    if level not in ("server", "location"):
        raise HTTPException(400, detail="Level must be 'server' or 'location'")
    if not NGINX_CONF_DIR.exists():
        raise HTTPException(503, detail="Nginx config dir not mounted — check /config/nginx volume")


@app.get("/api/auth-configs")
def list_auth_configs():
    """Return status (active/sample/new) for each provider × level."""
    result: dict[str, dict[str, str]] = {}
    for provider in AUTH_PROVIDERS:
        result[provider] = {
            "server":   _auth_status(provider, "server"),
            "location": _auth_status(provider, "location"),
        }
    return result


@app.get("/api/auth-configs/{provider}/{level}")
def get_auth_config(provider: str, level: str):
    _check_auth_args(provider, level)
    return {
        "provider": provider,
        "level":    level,
        "status":   _auth_status(provider, level),
        "content":  _auth_content(provider, level),
    }


@app.put("/api/auth-configs/{provider}/{level}")
def update_auth_config(provider: str, level: str, body: ConfigFileUpdate):
    _check_auth_args(provider, level)
    _auth_conf_path(provider, level).write_text(body.content)
    return {"provider": provider, "level": level, "message": "saved"}


@app.post("/api/auth-configs/{provider}/{level}/enable")
def enable_auth_config(provider: str, level: str):
    """Create .conf from sample or built-in template."""
    _check_auth_args(provider, level)
    conf    = _auth_conf_path(provider, level)
    content = _auth_content(provider, level)
    conf.write_text(content)
    return {"provider": provider, "level": level, "status": "active", "content": content}


# ── DNS config endpoints ──────────────────────────────────────────────────────

def _dns_path(filename: str) -> Path:
    """Resolve and validate a dns-conf filename (no path traversal)."""
    if not filename or "/" in filename or "\\" in filename:
        raise HTTPException(400, detail="Invalid filename")
    path = DNS_CONF_DIR / filename
    # Ensure the resolved path stays inside the dns-conf directory
    if not path.resolve().is_relative_to(DNS_CONF_DIR.resolve()):
        raise HTTPException(400, detail="Invalid filename")
    return path


@app.get("/api/dns-configs")
def list_dns_configs():
    if not DNS_CONF_DIR.exists():
        return {"files": [], "warning": f"DNS config directory not found: {DNS_CONF_DIR}"}
    files = []
    for path in sorted(DNS_CONF_DIR.iterdir()):
        if not path.is_file():
            continue
        is_sample = path.name.endswith(".sample")
        files.append({"filename": path.name, "is_sample": is_sample})
    return {"files": files}


@app.get("/api/dns-configs/{filename}")
def get_dns_config(filename: str):
    path = _dns_path(filename)
    if not path.exists():
        raise HTTPException(404, detail=f"{filename} not found")
    return {"filename": filename, "content": path.read_text()}


@app.put("/api/dns-configs/{filename}")
def update_dns_config(filename: str, body: ConfigFileUpdate):
    path = _dns_path(filename)
    if not path.exists():
        raise HTTPException(404, detail=f"{filename} not found")
    path.write_text(body.content)
    return {"filename": filename, "message": "saved"}


# ── Site conf endpoints ───────────────────────────────────────────────────────

def _site_path(filename: str) -> Path:
    """Resolve and validate a site-confs filename (no path traversal)."""
    if not filename or "/" in filename or "\\" in filename:
        raise HTTPException(400, detail="Invalid filename")
    path = SITE_CONF_DIR / filename
    if not path.resolve().is_relative_to(SITE_CONF_DIR.resolve()):
        raise HTTPException(400, detail="Invalid filename")
    return path


@app.get("/api/site-confs")
def list_site_confs():
    if not SITE_CONF_DIR.exists():
        return {"files": [], "warning": f"Site conf directory not found: {SITE_CONF_DIR}"}
    files = [
        {"filename": p.name}
        for p in sorted(SITE_CONF_DIR.iterdir())
        if p.is_file()
    ]
    return {"files": files}


@app.get("/api/site-confs/{filename}")
def get_site_conf(filename: str):
    path = _site_path(filename)
    if not path.exists():
        raise HTTPException(404, detail=f"{filename} not found")
    return {"filename": filename, "content": path.read_text()}


@app.put("/api/site-confs/{filename}")
def update_site_conf(filename: str, body: ConfigFileUpdate):
    path = _site_path(filename)
    if not path.exists():
        raise HTTPException(404, detail=f"{filename} not found")
    path.write_text(body.content)
    return {"filename": filename, "message": "saved"}


# ── Log endpoints ────────────────────────────────────────────────────────────

@app.get("/api/logs")
def list_logs():
    if not LOG_DIR.exists():
        return {"files": [], "warning": f"Log directory not found: {LOG_DIR}"}
    files = []
    for path in sorted(LOG_DIR.rglob("*.log")):
        if path.is_file():
            rel = path.relative_to(LOG_DIR)
            files.append({
                "filepath": str(rel),
                "filename": path.name,
                "subdir":   str(rel.parent) if rel.parent != Path(".") else "",
            })
    return {"files": files}


@app.get("/api/logs/{filepath:path}")
def get_log(filepath: str):
    path = (LOG_DIR / filepath).resolve()
    if not path.is_relative_to(LOG_DIR.resolve()):
        raise HTTPException(400, detail="Invalid path")
    if not path.exists() or not path.is_file():
        raise HTTPException(404, detail=f"{filepath} not found")

    size = path.stat().st_size
    if size > LOG_MAX_BYTES:
        with path.open("rb") as f:
            f.seek(size - LOG_MAX_BYTES)
            raw = f.read()
        # Skip the partial first line
        content = raw.decode("utf-8", errors="replace")
        newline = content.find("\n")
        content = content[newline + 1:] if newline != -1 else content
        truncated = True
    else:
        content = path.read_text(errors="replace")
        truncated = False

    return {
        "filepath":  filepath,
        "content":   content,
        "size":      size,
        "truncated": truncated,
    }


# ── Fail2ban endpoints ────────────────────────────────────────────────────────

def _fail2ban_client(args: list[str]) -> str:
    """Run fail2ban-client inside the SWAG container; return stdout, raise on error."""
    if docker_sdk is None:
        raise HTTPException(503, detail="Docker SDK not installed in this image")
    try:
        client = docker_sdk.from_env()
    except Exception as e:
        raise HTTPException(503, detail=f"Docker socket unavailable. Mount /var/run/docker.sock:ro\n{e}")
    try:
        container = client.containers.get(SWAG_CONTAINER)
    except Exception:
        raise HTTPException(503, detail=f"Container '{SWAG_CONTAINER}' not found. Set SWAG_CONTAINER_NAME env var.")

    res = container.exec_run(["fail2ban-client"] + args)
    out = res.output.decode(errors="replace") if res.output else ""
    if res.exit_code != 0:
        raise HTTPException(502, detail=f"fail2ban-client {' '.join(args)} failed:\n{out.strip()}")
    return out


def _parse_jail_list(output: str) -> list[str]:
    m = re.search(r"Jail list:\s*(.*)", output)
    if not m:
        return []
    return [j.strip() for j in m.group(1).split(",") if j.strip()]


def _parse_jail_status(output: str) -> dict:
    def num(label: str) -> int:
        m = re.search(rf"{label}:\s*(\d+)", output)
        return int(m.group(1)) if m else 0

    banned_m = re.search(r"Banned IP list:\s*(.*)", output)
    banned_ips = banned_m.group(1).split() if (banned_m and banned_m.group(1).strip()) else []

    file_m = re.search(r"File list:\s*(.*)", output)
    file_list = file_m.group(1).strip() if file_m else ""

    return {
        "currently_failed": num("Currently failed"),
        "total_failed":     num("Total failed"),
        "currently_banned": num("Currently banned"),
        "total_banned":     num("Total banned"),
        "banned_ips":       banned_ips,
        "file_list":        file_list,
    }


def _validate_ip(ip: str) -> str:
    ip = ip.strip()
    # Allow IPv4/IPv6 chars + CIDR; reject anything that could be an arg/flag
    if not ip or not re.fullmatch(r"[0-9a-fA-F:.\/]+", ip):
        raise HTTPException(400, detail="Invalid IP address")
    return ip


@app.get("/api/fail2ban/status")
def fail2ban_status():
    overview = _fail2ban_client(["status"])
    jails = []
    for name in _parse_jail_list(overview):
        detail = _fail2ban_client(["status", name])
        jails.append({"name": name, **_parse_jail_status(detail)})
    return {"jails": jails}


@app.post("/api/fail2ban/{jail}/unban")
def fail2ban_unban(jail: str, body: IpRequest):
    ip = _validate_ip(body.ip)
    _fail2ban_client(["set", jail, "unbanip", ip])
    return {"jail": jail, "ip": ip, "message": "unbanned"}


@app.post("/api/fail2ban/{jail}/ban")
def fail2ban_ban(jail: str, body: IpRequest):
    ip = _validate_ip(body.ip)
    _fail2ban_client(["set", jail, "banip", ip])
    return {"jail": jail, "ip": ip, "message": "banned"}


# ── Fail2ban config files ─────────────────────────────────────────────────────

def _fail2ban_conf_path(filepath: str) -> Path:
    if not filepath or ".." in filepath or filepath.startswith("/") or "\\" in filepath:
        raise HTTPException(400, detail="Invalid path")
    path = (FAIL2BAN_DIR / filepath).resolve()
    if not path.is_relative_to(FAIL2BAN_DIR.resolve()):
        raise HTTPException(400, detail="Invalid path")
    return path


@app.get("/api/fail2ban-configs")
def list_fail2ban_configs():
    if not FAIL2BAN_DIR.exists():
        return {"files": [], "warning": f"fail2ban directory not found: {FAIL2BAN_DIR}"}
    files = []
    for pattern in ("*.local", "*.conf"):
        for p in sorted(FAIL2BAN_DIR.glob(pattern)):
            if p.is_file():
                files.append({"filepath": p.name})
    return {"files": files}


@app.get("/api/fail2ban-configs/{filepath:path}")
def get_fail2ban_config(filepath: str):
    path = _fail2ban_conf_path(filepath)
    if not path.exists() or not path.is_file():
        raise HTTPException(404, detail=f"{filepath} not found")
    return {"filepath": filepath, "content": path.read_text()}


@app.put("/api/fail2ban-configs/{filepath:path}")
def update_fail2ban_config(filepath: str, body: ConfigFileUpdate):
    path = _fail2ban_conf_path(filepath)
    if not path.exists() or not path.is_file():
        raise HTTPException(404, detail=f"{filepath} not found")
    path.write_text(body.content)
    return {"filepath": filepath, "message": "saved"}


# ── Health ────────────────────────────────────────────────────────────────────

@app.get("/api/health")
def health():
    return {
        "status": "ok",
        "conf_dir": str(PROXY_CONF_DIR),
        "conf_dir_exists": PROXY_CONF_DIR.exists(),
        "nginx_conf_dir": str(NGINX_CONF_DIR),
        "nginx_conf_dir_exists": NGINX_CONF_DIR.exists(),
        "dns_conf_dir": str(DNS_CONF_DIR),
        "dns_conf_dir_exists": DNS_CONF_DIR.exists(),
        "site_conf_dir": str(SITE_CONF_DIR),
        "site_conf_dir_exists": SITE_CONF_DIR.exists(),
        "docker_available": docker_sdk is not None,
        "swag_container": SWAG_CONTAINER,
    }


# Serve built frontend in production
static_dir = Path("static")
if static_dir.exists():
    app.mount("/", StaticFiles(directory=str(static_dir), html=True), name="static")
