from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel
from typing import Literal, Optional
import json
import os
from pathlib import Path

PROXY_CONF_DIR = Path(os.getenv("PROXY_CONF_DIR", "/config/nginx/proxy-confs"))
METADATA_PREFIX = "## SWAG-UI: "

app = FastAPI(title="SWAG Proxy UI")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)


class ProxyHost(BaseModel):
    name: str
    type: Literal["subdomain", "subfolder"] = "subdomain"
    upstream_host: str
    upstream_port: int = 80
    upstream_proto: Literal["http", "https"] = "http"
    websocket: bool = False
    enabled: bool = True
    custom_location: Optional[str] = None


def conf_filename(name: str, type_: str, enabled: bool) -> str:
    suffix = "" if enabled else ".disabled"
    return f"{name}.{type_}.conf{suffix}"


def find_conf_file(name: str) -> Optional[tuple[Path, bool, str]]:
    for type_ in ["subdomain", "subfolder"]:
        for enabled in [True, False]:
            path = PROXY_CONF_DIR / conf_filename(name, type_, enabled)
            if path.exists():
                return path, enabled, type_
    return None


def parse_metadata(path: Path) -> Optional[dict]:
    try:
        first_line = path.open().readline().strip()
        if first_line.startswith(METADATA_PREFIX):
            return json.loads(first_line[len(METADATA_PREFIX):])
    except Exception:
        pass
    return None


def generate_subdomain_conf(host: ProxyHost) -> str:
    meta = json.dumps(host.model_dump())
    ws = (
        "\n        proxy_set_header Upgrade $http_upgrade;"
        "\n        proxy_set_header Connection $connection_upgrade;"
        if host.websocket else ""
    )
    return f"""{METADATA_PREFIX}{meta}
## Generated by SWAG Proxy UI

server {{
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name {host.name}.*;

    include /config/nginx/ssl.conf;

    client_max_body_size 0;

    location / {{
        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app {host.upstream_host};
        set $upstream_port {host.upstream_port};
        set $upstream_proto {host.upstream_proto};
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;{ws}
    }}
}}
"""


def generate_subfolder_conf(host: ProxyHost) -> str:
    meta = json.dumps(host.model_dump())
    loc = host.custom_location or f"/{host.name}"
    return f"""{METADATA_PREFIX}{meta}
## Generated by SWAG Proxy UI

location ^~ {loc}/ {{
    include /config/nginx/proxy.conf;
    include /config/nginx/resolver.conf;
    set $upstream_app {host.upstream_host};
    set $upstream_port {host.upstream_port};
    set $upstream_proto {host.upstream_proto};
    proxy_pass $upstream_proto://$upstream_app:$upstream_port;
    proxy_redirect off;
}}
"""


@app.get("/api/proxy-hosts")
def list_proxy_hosts():
    if not PROXY_CONF_DIR.exists():
        return {"hosts": [], "warning": f"Config directory not found: {PROXY_CONF_DIR}"}

    hosts = []
    seen: set[str] = set()

    for path in sorted(PROXY_CONF_DIR.iterdir()):
        filename = path.name
        enabled = not filename.endswith(".disabled")
        name = filename[:-len(".disabled")] if not enabled else filename

        if name.endswith(".subdomain.conf"):
            host_name = name[:-len(".subdomain.conf")]
            host_type = "subdomain"
        elif name.endswith(".subfolder.conf"):
            host_name = name[:-len(".subfolder.conf")]
            host_type = "subfolder"
        else:
            continue

        if host_name in seen:
            continue
        seen.add(host_name)

        meta = parse_metadata(path)
        if meta:
            meta["enabled"] = enabled
            hosts.append({"managed": True, **meta})
        else:
            hosts.append({"managed": False, "name": host_name, "type": host_type, "enabled": enabled})

    return {"hosts": hosts}


@app.post("/api/proxy-hosts", status_code=201)
def create_proxy_host(host: ProxyHost):
    if find_conf_file(host.name):
        raise HTTPException(400, detail=f"Proxy host '{host.name}' already exists")

    path = PROXY_CONF_DIR / conf_filename(host.name, host.type, host.enabled)
    content = generate_subdomain_conf(host) if host.type == "subdomain" else generate_subfolder_conf(host)
    path.write_text(content)
    return host


@app.get("/api/proxy-hosts/{name}")
def get_proxy_host(name: str):
    result = find_conf_file(name)
    if not result:
        raise HTTPException(404, detail=f"Proxy host '{name}' not found")
    path, enabled, _ = result
    meta = parse_metadata(path)
    if not meta:
        raise HTTPException(422, detail="Conf file has no SWAG-UI metadata (unmanaged file)")
    meta["enabled"] = enabled
    return meta


@app.put("/api/proxy-hosts/{name}")
def update_proxy_host(name: str, host: ProxyHost):
    result = find_conf_file(name)
    if not result:
        raise HTTPException(404, detail=f"Proxy host '{name}' not found")
    old_path, _, _ = result
    old_path.unlink()

    path = PROXY_CONF_DIR / conf_filename(host.name, host.type, host.enabled)
    content = generate_subdomain_conf(host) if host.type == "subdomain" else generate_subfolder_conf(host)
    path.write_text(content)
    return host


@app.delete("/api/proxy-hosts/{name}", status_code=204)
def delete_proxy_host(name: str):
    result = find_conf_file(name)
    if not result:
        raise HTTPException(404, detail=f"Proxy host '{name}' not found")
    result[0].unlink()


@app.post("/api/proxy-hosts/{name}/toggle")
def toggle_proxy_host(name: str):
    result = find_conf_file(name)
    if not result:
        raise HTTPException(404, detail=f"Proxy host '{name}' not found")
    path, enabled, host_type = result
    new_path = PROXY_CONF_DIR / conf_filename(name, host_type, not enabled)
    path.rename(new_path)
    return {"name": name, "enabled": not enabled}


@app.get("/api/proxy-hosts/{name}/conf")
def get_conf_content(name: str):
    result = find_conf_file(name)
    if not result:
        raise HTTPException(404, detail=f"Proxy host '{name}' not found")
    return {"content": result[0].read_text(), "filename": result[0].name}


@app.get("/api/health")
def health():
    return {
        "status": "ok",
        "conf_dir": str(PROXY_CONF_DIR),
        "conf_dir_exists": PROXY_CONF_DIR.exists(),
    }


# Serve built frontend when running in production
static_dir = Path("static")
if static_dir.exists():
    app.mount("/", StaticFiles(directory=str(static_dir), html=True), name="static")
